name: Shipping Service CI
# ketika
on:
  # ada push
  push:
    # ke branch
    branches:
      # ini
      - shipping-service

# Maka jalankan
jobs:
  # Build App
  build-app-shipping-service:
    # di ubuntu
    runs-on: ubuntu-latest
    # dengan langkah-langkah sebagai berikut
    steps:
      # Checkout kode dengan actions/checkout@v2
    - uses: actions/checkout@v2
      # Login ke GithubPackages
    - name: Log in to GithubPackages
      # dengan docker/login-action@v1
      uses: docker/login-action@v1
      # dengan username dan password
      with:
        registry: ghcr.io
        username: thearkaid
        password: ${{ secrets.PAT }}
    # Dan build dan push
    - name: Build and push
      # dengan docker
      run: |
        docker build -t ghcr.io/thearkaid/shipping-service:latest .
        docker push ghcr.io/thearkaid/shipping-service:latest
