name: CI/CD Pipeline for KarsaJobs UI
# ketika
on:
  # ada push
  push:
    # ke branch
    branches:
      # ini
      - karsajobs-ui
# Maka jalankan
jobs:
  # Link/semacam perbaikan tata tulis perkodean
  lint:
    # Dijalankan di Ubuntu
    runs-on: ubuntu-latest
    # dengan langkah-langkah sebagai berikut
    steps:
      # Checkout kode dengan actions/checkout@v2
      - uses: actions/checkout@v2
      # Setup Node.js
      - name: Setup Node.js
        # Dengan actions/setup-node@v2
        uses: actions/setup-node@v2
        # dan
        with:
          # versi Node.js 14 (sesuai Dockerfile)
          node-version: '14'
      # Install dependencies
      - name: Install dependencies
        # dengan npm install
        run: npm install
      # Baru jalankan lint
      - name: Lint
        # dengan npm run lint
        run: npm run lint
  # Build dan push Docker image
  build-and-push:
    # Setelah lint selesai, maka 
    needs: lint
    # Dijalankan di Ubuntu
    runs-on: ubuntu-latest
    # dengan langkah-langkah sebagai berikut
    steps:
      # Checkout kode dengan actions/checkout@v2
      - uses: actions/checkout@v2
      # Setup Node.js
      - name: Setup Node.js
        # Dengan actions/setup-node@v2
        uses: actions/setup-node@v2
        # dan
        with:
          # versi Node.js 14 (sesuai Dockerfile)
          node-version: '14'
          # download nya dari sini
          registry-url: https://npm.pkg.github.com
          # dengan scope thearkaid/user github
          scope: 'thearkaid'
      # Install dependencies
      - name: Install dependencies
        # dengan npm install
        run: npm install
      # Build
      - name: Build
        # dengan npm run build
        run: npm run build
      # Log in ke GitHub Container Registry
      - name: Log in to GitHub Container Registry
        # dengan docker/login-action@v1
        uses: docker/login-action@v1
        # dan
        with:
          # registry nya
          registry: ghcr.io
          # username nya
          username: thearkaid
          # password nya
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build dan push Docker image
      - name: Build and push Docker image
        # dengan docker
        run: |
          docker build -t ghcr.io/thearkaid/karsajobs-ui:latest . # Sesuaikan dengan username GitHub Anda
          docker push ghcr.io/thearkaid/karsajobs-ui:latest # Sesuaikan dengan username GitHub Anda
