name: KarsaJobs CI Backend
# ketika
on:
  # ada push
  push:
    # ke branch
    branches:
      # ini
      - karsajobs

# Maka jalankan
jobs:
  # Lint Dockerfile
  lint-dockerfile:
    # di ubuntu
    runs-on: ubuntu-latest
    # dengan langkah-langkah sebagai berikut
    steps:
      # Checkout kode dengan actions/checkout@v2
    - uses: actions/checkout@v2
      # Lint Dockerfile dengan hadolint/hadolint-action@v1.5.0
    - name: Lint Dockerfile
      # dengan package ini
      uses: hadolint/hadolint-action@v1.5.0
      # dan Dockerfile
      with:
        dockerfile: Dockerfile
  # Test App
  test-app:
    # di ubuntu
    runs-on: ubuntu-latest
    # dengan langkah-langkah sebagai berikut
    steps:
      # Checkout kode dengan actions/checkout@v2
    - uses: actions/checkout@v2
    # Dan test
    - name: Test App
      # dengan go test -v -short --count=1 $(go list ./...)
      run: |
        go test -v -short --count=1 $(go list ./...)
  # Build App
  build-app-karsajobs:
    # di ubuntu
    runs-on: ubuntu-latest
    # dengan langkah-langkah sebagai berikut
    steps:
      # Checkout kode dengan actions/checkout@v2
    - uses: actions/checkout@v2
      # Login ke GithubPackages
    - name: Log in to GithubPackages
      # dengan docker/login-action@v1
      uses: docker/login-action@v1
      # dengan username dan password
      with:
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PASSWORD }}
    # Dan build dan push
    - name: Build and push
      # dengan docker
      run: |
        docker build -t ghcr.io/thearkaid/${{ secrets.GITHUB_USERNAME }}/karsajobs:latest .
        docker push ghcr.io/thearkaid/${{ secrets.GITHUB_USERNAME }}/karsajobs:latest
